var links = [
  "patorjk.com/games/snake/",
  "arcade.ly/games/asteroids/",
  "free80sarcade.com/pacman.php",
  "free80sarcade.com/galaga.php",
  "tetris.com/play-tetris",
  "play2048.co/",
  "free80sarcade.com/sonic.php",
  "arcadespot.com/game/dig-dug/",
  "froggerclassic.appspot.com/",
  "archives.obs-us.com/obs/english/books/holt/books/maze/index.html",
  "foddy.net/Athletics.html?webgl=true",
  "entanglement.gopherwoodstudios.com/en-US-index.html",
  "mackerelmediafish.com/#",
  "catmario.eu/",
  "poptropica.com/",
  "cprewritten.net/",
  "slither.io/",
  "agar.io/?#ffa",
  "zombs.io/",
  "warbot.io/",
  "shellshock.io/",
  "deeeep.io/",
  "jigsawplanet.com/",
  "animaljam.com/en",
  "sites.google.com/view/frivgo/earn-to-die-2",
  "roblox.com/",
  "totaljerkface.com/happy_wheels.tjf",
  "teamfortress.com/",
  "plugplay.ch/",
  "minecraft.net/en-us/",
  "signup.na.leagueoflegends.com/en/signup/index#/",
  "playoverwatch.com/en-us/",
  "poki.com/en/g/sky-chasers",
  "kingdomofloathing.com/login.php?loginid=d6aad487aba647ff86a12145a1138708",
  "kongregate.com/games/graebor/sort-the-court",
  "mateuszskutnik.com/daymare-town/",
  "willyoupressthebutton.com/",
  "youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO",
  "poki.com/en/g/the-impossible-quiz-2",
  "fallguys.com/",
  "flappybird.io/",
  "geometrydash-free.com/",
  "solitaired.com/",
  "247blackjack.com/",
  "atari.com/",
  "cubefield.org.uk/#:~:text=Cubefield%20is%20a%20simple%20but,speed%20goes%20up%20and%20up!",
  "play.typeracer.com/",
  "webkinz.com/",
  "woodblockpuzzle.com/onlinegame/",
  "doodlejumpgame.com/",
  "websudoku.com/",
  "chess.com/",
  "coolmathgames.com/",
  "gametable.org/games/checkers/",
  "vegasslotsonline.com/table-games/craps/",
  "store.steampowered.com/",
  "agame.com/games/anime_and_manga_games",
  "worldofwarcraft.com/en-us/",
  "thezen.zone/",
  "crayta.com/?gclid=Cj0KCQjwsqmEBhDiARIsANV8H3aQW5TUz453XNs-KuXyLW9VQz__2te6YIK5mxhps4rIFs5cgb7r93saAsbTEALw_wcB",
  "crazygames.com/t/cat",
  "eviebot.com/en/",
  "agame.com/game/scary-maze",
  "boardgamesonline.net/Online/monopoli",
  "toytheater.com/snakes-and-ladders/",
  "arcadespot.com/game/clue/",
  "jackboxgames.com/?gclid=Cj0KCQjwsqmEBhDiARIsANV8H3ZC-anArz4My6K_e7Gaoh6scsKCaKyWD_S43-qkPRPMWFC_R70s2a4aArRuEALw_wcB",
  "kahoot.it/?_ga=2.7818738.1140171908.1619738009-347009978.1619738009&deviceId=5ce290fe-4e15-4c04-bea8-20d6a7f2dadfR&sessionId=1619738010633",
  "cbc.ca/kidscbc2/content/games/new_soccer/index.html",
  "cbc.ca/kids/games/play/gravity-escapes"
];

var openSite = function () {
  // get a random number between 0 and the number of links
  var randIdx = Math.random() * links.length;
  // round it, so it can be used as array index
  randIdx = parseInt(randIdx, 10);
  // construct the link to be opened
  var link = "http://" + links[randIdx];

  var win = window.open(link, "_blank");
  win.focus();
};
